services:
  backend:
    build: .
    container_name: unwritten-legends-backend
    restart: always
    env_file: .env
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    networks:
      - ul_network:
          - external: true
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
