services:
  backend:
    build: .
    container_name: unwritten-legends-backend
    restart: always
    env_file: .env
    ports:
      - '3000:3000'
    networks:
      - ul_network
    volumes:
      - ./src:/app/src  # ✅ Nur den src-Ordner mounten, damit Code-Änderungen sofort übernommen werden
    command: npm run dev

networks:
  ul_network:
    external: true
