version: '3.8'

services:
  status-dashboard:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '80:80'
    environment:
      - NODE_ENV=production
    volumes:
      - ./src:/app/src
    networks:
      - ul_network

networks:
  ul_network:
    external: true
