version: '3.8'
services:
  frontend:
    build: .
    container_name: frontend-module
    ports:
      - '80:80'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
