FROM node
WORKDIR /app

# Dependencies installieren
COPY package.json ./
RUN npm install 

# 📌 Hier den gesamten Quellcode kopieren
COPY . . 

RUN mkdir -p ./dist/
RUN mv ./src/views ./dist/
RUN mv ./public ./dist/public

# TypeScript kompilieren
RUN npm run build

# Startbefehl
EXPOSE 80
CMD ["node", "dist/app.js"]
